name: ci

on:
  push:
  pull_request:

jobs:
  build-l1-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      - run: npm run test:l1
      - run: npm run size
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
